### ISSUE TITLE
Does this still work with OS X Mavericks?

### ISSUE THREAD

**Issue by davidrivers** [tell-k/vim-browsereload-mac#3]
I was unable to locate the setting mentioned in the README (_System Preferences > Universal Access > "Enable access for assistive devices"_) and assume this is why I can't get this to work in 10.9.1. When running :FirefoxReload, something definitely happens (window switching ensues), but no refreshed browser tab.

Any ideas?

**Comment by tell-k** [comment]
Hi DavidRivers. 

After upgrading to the OS X 10.9 Mavericks. "Universal Access" is no longer. 
I can now be set from the "Security & Privacy> Accessbillity> Privacy" instead. 
From here, please check the Editor that you are using. I will update within the document also close. 

http://www.tekrevue.com/how-to-enable-access-for-assistive-devices-in-os-x-mavericks/

When i checked "Terminal.app",  I was able to reload. 

![Settings Image](http://dl.dropbox.com/u/540566/Screenshots/2yei3mnbfcc3.png)

Thank you for the question

**Comment by tell-k** [comment]
Did this fix the problem? Can i close this issue?
