### ISSUE TITLE
I'd like to modify this project.

### ISSUE THREAD

**Issue by ghost** [tell-k/vim-browsereload-mac#4]
Hi.
May I remodel this project '[_vim-browsereload-mac_](https://github.com/tell-k/vim-browsereload-mac)' only for me and manage in my repository?
What I'll do is not for your project but for me. (I'm going to pursue my usability)
So probably this won't become contribution toward you.
Finally,  I’m Japanese student, therefore I may not be able to  communicate to you completely in English.
I’m so sorry.

**Comment by tell-k** [comment]
@am4ne Sorry too late my reply. 

> only for me and manage in my repository?

Of course, let's try it! as you want.
